Repository picoe/Eto, pull requests merged in 2024-09, with the labels that each got.

#2682 Wpf: Fix issue restoring column focus if the column has been removed
  .github/workflows/build.yml
  src/Eto.Wpf/Forms/Controls/GridHandler.cs
Labels: bug

#2683 Wpf: Ignore exceptions when calling GC.TryStartNoGCRegion
  src/Eto.Wpf/Forms/Controls/TextBoxHandler.cs
Labels: wpf, bug

#2644 Fix an event handler leak in `Binding.RemovePropertyEvent`
  src/Eto/Forms/Binding/Binding.helpers.cs
  src/Eto/Forms/Binding/DelegateBinding.cs
  src/Eto/Forms/Binding/PropertyNotifyHelper.cs
  test/Eto.Test/UnitTests/Forms/Bindings/BindingHelpersTests.cs
  test/Eto.Test/UnitTests/Forms/Bindings/DelegateBindingTests.cs
Labels: enhancement, bug

#2684 Window OnLoadComplete and GetPreferredSize improvements
  src/Eto.Gtk/Forms/DialogHandler.cs
  src/Eto.Gtk/Forms/FormHandler.cs
  src/Eto.Gtk/Forms/GtkControl.cs
  src/Eto.Gtk/Forms/GtkWindow.cs
  src/Eto.Mac/Forms/DialogHandler.cs
  src/Eto.Mac/Forms/FormHandler.cs
  src/Eto.Mac/Forms/MacView.cs
  src/Eto.Mac/Forms/MacWindow.cs
  src/Eto.WinForms/Forms/WindowHandler.cs
  src/Eto.Wpf/Forms/DialogHandler.cs
  src/Eto.Wpf/Forms/FormHandler.cs
  src/Eto.Wpf/Forms/WpfWindow.cs
  src/Eto/Forms/Controls/Control.cs
  src/Eto/Forms/Dialog.cs
  src/Eto/Forms/Form.cs
  src/Eto/Forms/Window.cs
  test/Eto.Test/Sections/Behaviors/WindowsSection.cs
  test/Eto.Test/Sections/UnitTestPanel.cs
  test/Eto.Test/UnitTests/Forms/DialogTests.cs
  test/Eto.Test/UnitTests/Forms/FormTests.cs
  test/Eto.Test/UnitTests/Forms/WindowTests.cs
  test/Eto.Test/UnitTests/TestBase.cs
Labels: enhancement, bug

#2685 Wpf: Allow DataGrid and Window background to be styled
  src/Eto.Wpf/Forms/ColorDialogHandler.cs
  src/Eto.Wpf/Forms/Controls/GridHandler.cs
  src/Eto.Wpf/Forms/Controls/TreeGridViewHandler.cs
  src/Eto.Wpf/Forms/WpfWindow.cs
  src/Eto.Wpf/themes/controls/DataGrid.xaml
  src/Eto.Wpf/themes/controls/Window.xaml
  src/Eto.Wpf/themes/controls/XceedColorDialog.xaml
  src/Eto.Wpf/themes/generic.xaml
Labels: bug
