Repository picoe/Eto, pull requests merged in 2025-01, with the labels that each got.

#2722 Allow disposing multiple times
  src/Eto/Widget.cs
Labels: bug

#2725 Wpf: Allow intrinsic key behavior of menu shortcut keys when item is disabled
  src/Eto.Wpf/Forms/Menu/MenuItemHandler.cs
  src/Eto.Wpf/Forms/WpfWindow.cs
  test/Eto.Test/UnitTests/Forms/MenuItemTests.cs
Labels: wpf

#2728 Mac: Graphics.FillPath() should use the FillMode of the GraphicsPath
  src/Eto.Mac/Drawing/GraphicsHandler.cs
  test/Eto.Test/UnitTests/Drawing/GraphicsPathTests.cs
Labels: bug

#2730 Don't when running tests with the test app
  test/Eto.Test/UnitTests/TestBase.cs
Labels: bug

#2733 Mac: Setting Form.Owner shouldn't make it visible if previously hidden
  src/Eto.Mac/Forms/MacWindow.cs
  test/Eto.Test/UnitTests/Forms/FormTests.cs
Labels: mac, bug
